### ISSUE TITLE
Please check info about this GitHub Action

### ISSUE THREAD

**Issue by varunsh-coder** [ljharb/require-allow-edits#3]
Hi @ljharb 

I am collating security related information about GitHub Actions to calculate minimum GITHUB_TOKEN permissions and restrict outbound traffic to allowed domains. Request you to please check info about couple of your Actions [here](https://github.com/step-security/secure-workflows/tree/main/knowledge-base/ljharb) - specifically the reasons for the token permissions and outbound calls. If something looks off or needs to be changed, do let me know. Thanks!

You can try pasting the workflows in this repo [here](https://app.stepsecurity.io) to get minimum token permissions based on the data in the knowledge base.

**Comment by ljharb** [comment]
Those seem right to me.

I'm not sure the rebase action needs "write", unless that's because git itself writes files during a rebase?

**Comment by varunsh-coder** [comment]
> Those seem right to me.
> 
> I'm not sure the rebase action needs "write", unless that's because git itself writes files during a rebase?

I tried with `contents: read` and it failed. It is the [`git push`](https://github.com/ljharb/rebase/blob/6ca8681dc61847335eb68c8e43f4becb0911c091/entrypoint.sh#L93) that needs write access. 
https://github.com/varunsh-coder/actions-playground/runs/4397392953?check_suite_focus=true#step:6:57
