### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by prisis** [ljharb/require-allow-edits#4]
Hey :), is it possible to release the version 1.0.3 as a tag?

**Comment by ljharb** [comment]
It is one already https://github.com/ljharb/require-allow-edits/releases/tag/v1.0.3

**Comment by prisis** [comment]
![Screenshot_20230930-082518.png](https://github.com/ljharb/require-allow-edits/assets/2716058/2079b07b-cc9e-4f84-8205-3eba6e52b85a)

Funny, github shows only this 😅

**Comment by ljharb** [comment]
That’s not tags, that’s Releases. Those aren’t required to use anything.
